language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
    - .cache
script: yarn build
git:
  depth: 3
deploy:
  provider: netlify
  site: usaco-guide
  dir: public/
  edge: true
  prod: false
