name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn
      - run: yarn build
      - run: yarn serve &
      - run: pub global activate linkcheck

      - name: Check Links
        run: sleep 15 && $HOME/.pub-cache/bin/linkcheck :9000

#      - name: Check Links
#        uses: wunderundfitzig/linkcheck-action@v1
#        with:
#          arguments: '--net=host :9000'